version: "3.5"

services:
  test:
    image: gl-exporter-test:latest
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - octofactory.service.private-us-east-1.github.net/github-golden-docker/github-gl-exporter:gl-exporter-test-latest
