source 'https://rubygems.org'

# Specify your gem's dependencies in gl_exporter.gemspec
gemspec

gem 'pry-byebug'#, '~> 3.4.0'
gem 'vcr'
gem 'rspec'
gem 'webmock'
gem 'pry-rescue'
gem 'pry-stack_explorer'
