FROM ruby:3.2.1
LABEL Maintainer="GitHub Services <services@github.com>"
LABEL Description="gl-exporter is a tool for exporting GitLab repositories to be imported by ghe-migrator."

# Set HTTP(S) Proxy
ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTPS_PROXY

# Run updates
RUN apt-get update -qqy
RUN apt-get upgrade -qqy

# Install packages
RUN apt-get -qqy --no-install-recommends install cmake nano

# Get gl-exporter
COPY ./ /gl-exporter/
WORKDIR /gl-exporter

# Install bundler
RUN gem install --no-document bundler

# Run bootstrap
RUN chmod +x script/bootstrap
RUN script/bootstrap

