name: Export GitLab Repos

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract project names from issue
        if: github.event_name == 'issues'
        run: |
          echo "Extracting project names and namespaces from issue..."
          echo "${{ github.event.issue.body }}" > issue_body.txt

          # Sanitize and format the issue body
          sed -i 's/\r//g' issue_body.txt  # Remove carriage return if present
          sed -i 's/, /,/g' issue_body.txt  # Remove spaces after commas
          sed -i 's/\s\+/\n/g' issue_body.txt  # Convert spaces between lines to newline

          # Extract comma-separated values from the sanitized issue body
          grep -oP '[^,]+,[^,]+' issue_body.txt > export_list.csv

          echo "Generated export_list.csv with the following contents:"
          cat export_list.csv

      - name: Make output directory
        run: mkdir -p output

      - name: Move CSV to output directory
        run: mv export_list.csv output/

      - name: Verify CSV file contents
        run: |
          if [[ ! -f output/export_list.csv ]]; then
            echo "Error: CSV file 'output/export_list.csv' not found."
            exit 1
          else
            echo "CSV file found:"
            cat output/export_list.csv
          fi

      - name: Set up GitLab variables
        run: |
          echo "GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}" >> $GITHUB_ENV
          echo "GITLAB_API_PRIVATE_TOKEN=${{ secrets.GITLAB_API_PRIVATE_TOKEN }}" >> $GITHUB_ENV
          echo "GITLAB_API_ENDPOINT=${{ secrets.GITLAB_API_ENDPOINT }}" >> $GITHUB_ENV
          echo "GITLAB_USERNAME=${{ secrets.GITLAB_USERNAME }}" >> $GITHUB_ENV

      - name: Make migration script executable
        run: chmod +x gitlab-exporter.sh

      - name: Run GitLab exporter script
        run: ./gitlab-exporter.sh

      - name: List Output Directory
        run: ls -la output

      - name: Upload Exported Archive
        uses: actions/upload-artifact@v3
        with:
          name: migration_archive
          path: output/migration_archive.tar.gz
