name: Export GitLab Repos

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract project names from issue
        if: github.event_name == 'issues'
        run: |
          echo "Extracting project names and namespaces from issue..."
          echo "${{ github.event.issue.body }}" > issue_body.txt

          # Debug: Check the issue body content
          echo "Issue body content:"
          cat issue_body.txt

          # Process and extract the list, removing unnecessary slashes/commas
          grep -oP '[^,]+,[^,]+' issue_body.txt | while read -r line; do
            # Remove trailing slashes and newlines
            line=$(echo "$line" | sed 's,/*$,,g' | tr -d '\r\n')
            if [[ "$line" == *","* ]]; then
              echo "\"$line\"" >> export_list.csv
            else
              echo "$line" >> export_list.csv
            fi
          done

          # Debug: Check the generated export_list.csv
          echo "Generated export_list.csv:"
          cat export_list.csv

      - name: Make output directory
        run: mkdir -p output

      - name: Move CSV to output directory
        run: |
          echo "Moving export_list.csv to output directory..."
          mv export_list.csv output/

          # Debug: Ensure the file is in the output directory
          if [[ -f output/export_list.csv ]]; then
            echo "export_list.csv moved successfully."
          else
            echo "Error: export_list.csv not found in output directory."
            exit 1
          fi

      - name: List contents of export_list.csv with line numbers
        run: |
          echo "Displaying export_list.csv with line numbers:"
          cat -n output/export_list.csv

      - name: Set up GitLab variables
        run: |
          echo "GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}" >> $GITHUB_ENV
          echo "GITLAB_API_PRIVATE_TOKEN=${{ secrets.GITLAB_API_PRIVATE_TOKEN }}" >> $GITHUB_ENV
          echo "GITLAB_API_ENDPOINT=${{ secrets.GITLAB_API_ENDPOINT }}" >> $GITHUB_ENV
          echo "GITLAB_USERNAME=${{ secrets.GITLAB_USERNAME }}" >> $GITHUB_ENV

      - name: Make migration script executable
        run: chmod +x gitlab-exporter.sh

      - name: Run GitLab exporter script
        run: ./gitlab-exporter.sh

      - name: List Output Directory
        run: ls -la output

      - name: Upload Exported Archive
        uses: actions/upload-artifact@v3
        with:
          name: migration_archive
          path: output/migration_archive.tar.gz
