name: Export GitLab Repos

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitLab variables
        run: |
          echo "GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=adi-pilot-migration" >> $GITHUB_ENV
          echo "NAMESPACE=avanthika127" >> $GITHUB_ENV

      - name: Make migration script executable
        run: chmod +x gitlab-exporter.sh

      - name: Run GitLab exporter script
        run: ./gitlab-exporter.sh

      - name: Upload Exported Archive
        uses: actions/upload-artifact@v3
        with:
          name: migration_archive
          path: ./output/migration_archive.tar.gz
